### PR TITLE
add webpackRequire

### PR DESCRIPTION
**Pull request by mathmakgakpak**
you can now do

```js
require("EventEmitter"); // EventEmitter
require("./settings/Bots.js"); // object
```
in console

Discord: mathias377#3326

### CODE REVIEW

**Comment by LostMyCode** [comment]
whats that?
using `require` is better than `import` usage or ?

**Comment by mathmakgakpak** [comment]
compile it and type in console
require("events")

**Comment by LostMyCode** [comment]
image

HSLO not loaded

**Comment by mathmakgakpak** [comment]
wot

**Comment by mathmakgakpak** [comment]
you had to change something besides this, because as I showed [img](https://cdn.discordapp.com/attachments/697756716984434759/742738266075431013/unknown.png ) works

**Pull request closed without merging**
